CREATE TABLE categoria (
	codigo BIGINT(30) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

INSERT INTO CATEGORIA (nome) VALUES ('Lazer');
INSERT INTO CATEGORIA (nome) VALUES ('Alimentação');
INSERT INTO CATEGORIA (nome) VALUES ('Supermercado');
INSERT INTO CATEGORIA (nome) VALUES ('Farmácia');
INSERT INTO CATEGORIA (nome) VALUES ('Outros');